### ISSUE TITLE
Dataset Area2_Bump: AttributeError: 'DataFrame' object has no attribute 'ctr_hold_bump'`

### ISSUE THREAD

**Issue by dddavid4real** [neurallatents/nlb_tools#18]
Hi, thank you for this great framework.

During running evaluation for dataset Area2_Bump, I run into the following error:
`Traceback (most recent call last):
  File "/data2404/gzr/home/code/neuroscience/neural-data-transformers/scripts/eval.py", line 153, in <module>
    target_dict = make_eval_target_tensors(dataset, dataset_name=dataset_name, train_trial_split='train', eval_trial_split='val', include_psth=True, save_file=False)
  File "/home/gzr/miniconda3/envs/neuro/lib/python3.10/site-packages/nlb_tools/make_tensors.py", line 698, in make_eval_target_tensors
    train_decode_mask = params['decode_masks'](dataset.trial_info[train_mask])
  File "/home/gzr/miniconda3/envs/neuro/lib/python3.10/site-packages/nlb_tools/make_tensors.py", line 66, in <lambda>
    'decode_masks': lambda x: np.stack([x.ctr_hold_bump == 0, x.ctr_hold_bump == 1]).T,
  File "/home/gzr/miniconda3/envs/neuro/lib/python3.10/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ctr_hold_bump'`

Could you help me provide any possible solution? Thank you once again.

**Comment by felixp8** [comment]
Hi! I haven't seen this issue before. Could you share what your `dataset.trial_info` looks like?

**Comment by dddavid4real** [comment]
Hi. Thank you for your response. Turns out I loaded the wrong dataset. Will close this issue.
